server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cskaoyanmall
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
pagehelper:
  helper-dialect: mysql
