mall:
  aliyun:
    access-key-id: LTAI4Fr5gfYhcVjLMqeRGbuT
    access-secret: IrkcHu6dZyrjPZRushgO76P5392HJ1
    url: https://cskaoyan.oss-cn-beijing.aliyuncs.com/
    oss:
      bucket: cskaoyan
      end-point: oss-cn-beijing.aliyuncs.com

